### ISSUE TITLE
Вынести логику в отдельный класс

### ISSUE THREAD

**Issue by sendelufa** [roman883/SkillboxJava#1]
https://github.com/roman883/SkillboxJava/blob/a15042224b8b97d19e736784ae81332db6c24001/ToDoList/src/main/java/main/TaskController.java#L28

обычно логика не располагается в контроллере, поэтому создайте пакет service  и в нем создайте класс, который будет работать с бд, делать к ней запросы и в ответ для контроллера выдавать только ResponseEntity 

по простому это выглядит так
```java
    @PostMapping(value = "/tasks/")
    public ResponseEntity add(Task task) {
        return repositoryService.addTask(task);
    }
```

возвраты в данном случае могут быть такими
```java
ResponseEntity(id, HttpStatus.OK);
ResponseEntity(error, HttpStatus.BAD_REQUEST);
```

и уже в самом классе **repositoryService** вы и должны обеспечить многопоточность

**Comment by roman883** [comment]
Добрый день!
Вынес логику в класс RepositoryService. Синхронизация, насколько я понимаю остается как была, то есть при обращении в репозиторий на изменение/удаление - синхронизация по TaskRepository (надеюсь правильно).
[https://github.com/roman883/SkillboxJava/commit/2877c616603cafd0ede9b929f0fd562ea2ab6195](url)
Также объединил с последним заданием - создать JAR архив, он создан и запускается, независимо от idea можно также создавать/удалять/изменять задачи.
[https://github.com/roman883/SkillboxJava/tree/master/ToDoList](url)
